// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-hero/ClassicCentered.tsx": () => import("../components/mockups/home-hero/ClassicCentered.tsx"),
  "./components/mockups/home-hero/EditorialGrid.tsx": () => import("../components/mockups/home-hero/EditorialGrid.tsx"),
  "./components/mockups/home-hero/SplitContent.tsx": () => import("../components/mockups/home-hero/SplitContent.tsx")
};
